build: off
environment:
        matrix:
                - PYTHON: "C:\\Python36"
init:
        - "ECHO %PYTHON% %PYTHON_VERSION% %PYTHON_ARCH%"
install:
        - "%PYTHON%\\python.exe -m pip install pylint"

test_script:
        - powershell /C ".\make.ps1 -interpreter '%PYTHON%\\python.exe' -lint $true"
